// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2Nt_xp3sqQQ7ifT0v7Qzl0M8mUtLwmo',
    appId: '1:825275570635:web:aeabc9ad9f5fe8859cbe4e',
    messagingSenderId: '825275570635',
    projectId: 'therapy-34561',
    authDomain: 'therapy-34561.firebaseapp.com',
    storageBucket: 'therapy-34561.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8phZGnzAwxFKvVbkXokaQ2E2pFG2L7Hk',
    appId: '1:825275570635:android:404650ef5410d7689cbe4e',
    messagingSenderId: '825275570635',
    projectId: 'therapy-34561',
    storageBucket: 'therapy-34561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLnVT2hMqvEXS4ClC-MLglHbMY3_OVYHk',
    appId: '1:825275570635:ios:80297702ddfeed6f9cbe4e',
    messagingSenderId: '825275570635',
    projectId: 'therapy-34561',
    storageBucket: 'therapy-34561.appspot.com',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLnVT2hMqvEXS4ClC-MLglHbMY3_OVYHk',
    appId: '1:825275570635:ios:80297702ddfeed6f9cbe4e',
    messagingSenderId: '825275570635',
    projectId: 'therapy-34561',
    storageBucket: 'therapy-34561.appspot.com',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc2Nt_xp3sqQQ7ifT0v7Qzl0M8mUtLwmo',
    appId: '1:825275570635:web:2ffd3965136e7a1c9cbe4e',
    messagingSenderId: '825275570635',
    projectId: 'therapy-34561',
    authDomain: 'therapy-34561.firebaseapp.com',
    storageBucket: 'therapy-34561.appspot.com',
  );
}
