// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUIbusm2xrZ26UrcyEurnpvWWbcGbXWW0',
    appId: '1:755259810622:web:84d8a1dc34b4930736826f',
    messagingSenderId: '755259810622',
    projectId: 'mintl4-39090',
    authDomain: 'mintl4-39090.firebaseapp.com',
    storageBucket: 'mintl4-39090.appspot.com',
    measurementId: 'G-VYJ121DXFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFAcrxfqNi2kFxsdCZzfWkUUSjlbAc_o',
    appId: '1:755259810622:android:8d907a4a7d26cfd836826f',
    messagingSenderId: '755259810622',
    projectId: 'mintl4-39090',
    storageBucket: 'mintl4-39090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkNSPxcXvFKZlqjGBa7rORI6AmNgE6NcQ',
    appId: '1:755259810622:ios:854394cace9b3d9436826f',
    messagingSenderId: '755259810622',
    projectId: 'mintl4-39090',
    storageBucket: 'mintl4-39090.appspot.com',
    iosClientId: '755259810622-8k94qudcegkk37q1i6getto0kkbe6v4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.try3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkNSPxcXvFKZlqjGBa7rORI6AmNgE6NcQ',
    appId: '1:755259810622:ios:854394cace9b3d9436826f',
    messagingSenderId: '755259810622',
    projectId: 'mintl4-39090',
    storageBucket: 'mintl4-39090.appspot.com',
    iosClientId: '755259810622-8k94qudcegkk37q1i6getto0kkbe6v4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.try3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUIbusm2xrZ26UrcyEurnpvWWbcGbXWW0',
    appId: '1:755259810622:web:c4e7e12c0ef8a6f336826f',
    messagingSenderId: '755259810622',
    projectId: 'mintl4-39090',
    authDomain: 'mintl4-39090.firebaseapp.com',
    storageBucket: 'mintl4-39090.appspot.com',
    measurementId: 'G-CTLBR8D0ZW',
  );

}